---

- name: Build hosts file form current host
  template: src={{ item }}.j2 dest=/etc/{{ item }} mode=0644 owner=root group=root
  with_items:
   - hosts
#  copy: src={{hosts_hosts_file}} dest=/etc/hosts
